from pathlib import Path
p=Path("lib/main_online.dart")
s=p.read_text()

def replace_once(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f"anchor missing: {label}")
    s=s.replace(old,new,1)

def replace_between(start,end,new,label):
    global s
    i=s.find(start)
    if i<0: raise SystemExit(f"start missing: {label}")
    j=s.find(end,i)
    if j<0: raise SystemExit(f"end missing: {label}")
    s=s[:i]+new+s[j:]

start=s.find('class FuelPdfReport {')
end=s.find('class AdminUsersOnlineScreen',start)
if start<0 or end<0: raise SystemExit('FuelPdfReport markers missing')
fuel_pdf=r'''class FuelPdfReport {
  static const Color _iconBlue=Color(0xFF08367C);
  static Future<Uint8List> _materialIconPng(IconData icon,Color color) async {const canvasSize=72.0,glyphSize=52.0;final recorder=ui.PictureRecorder(),canvas=ui.Canvas(recorder);final painter=TextPainter(text:TextSpan(text:String.fromCharCode(icon.codePoint),style:TextStyle(fontFamily:icon.fontFamily,package:icon.fontPackage,fontSize:glyphSize,color:color)),textDirection:ui.TextDirection.ltr,textAlign:TextAlign.center);painter.layout();painter.paint(canvas,ui.Offset((canvasSize-painter.width)/2,(canvasSize-painter.height)/2));final picture=recorder.endRecording(),image=await picture.toImage(canvasSize.toInt(),canvasSize.toInt()),data=await image.toByteData(format:ui.ImageByteFormat.png);image.dispose();picture.dispose();if(data==null)throw StateError('Falha ao preparar ícone para o PDF.');return data.buffer.asUint8List();}
  static String _br(dynamic v,{bool liters=false}){final n=_num(v),fixed=n.toStringAsFixed(1),parts=fixed.split('.'),raw=parts.first,chars=raw.split('').reversed.toList(),out=<String>[];for(var i=0;i<chars.length;i++){if(i>0&&i%3==0)out.add('.');out.add(chars[i]);}final r='${out.reversed.join()},${parts.length>1?parts[1]:'0'}';return liters?'$r L':r;}
  static String _nfs(Map<String,dynamic> ctx){final values=_rows(ctx['nfs']).map((x)=>'NF ${x['invoice_number']}${_hasValue(x['batch_number'])?' / Lote ${x['batch_number']}':''}').toSet().toList();return values.isEmpty?'-':values.join(' • ');}
  static Future<Uint8List> build(List<Map<String,dynamic>> items) async {
    final doc=pw.Document(),regular=pw.Font.helvetica(),bold=pw.Font.helveticaBold();final navy=PdfColor.fromHex('#062A69'),royal=PdfColor.fromHex('#0E58C7'),line=PdfColor.fromHex('#D9E2EE'),text=PdfColor.fromHex('#20242B');
    final iconSet=<IconData>[Icons.local_gas_station_rounded,Icons.local_shipping_outlined,Icons.location_city_outlined,Icons.location_on_outlined,Icons.water_drop_outlined,Icons.person_outline_rounded,Icons.speed_outlined,Icons.storage_outlined,Icons.assignment_outlined,Icons.draw_outlined,Icons.business_outlined,Icons.receipt_long_outlined,Icons.swap_horiz_rounded,Icons.precision_manufacturing_outlined];
    final blue=<int,pw.MemoryImage>{},white=<int,pw.MemoryImage>{};for(final i in iconSet){blue[i.codePoint]=pw.MemoryImage(await _materialIconPng(i,_iconBlue));}white[Icons.local_gas_station_rounded.codePoint]=pw.MemoryImage(await _materialIconPng(Icons.local_gas_station_rounded,Colors.white));
    pw.Widget icon(IconData d,{double size=22,bool isWhite=false}){final m=(isWhite?white:blue)[d.codePoint];return m==null?pw.SizedBox(width:size,height:size):pw.Image(m,width:size,height:size,fit:pw.BoxFit.contain);}
    pw.Widget row(IconData d,String label,String value,PdfColor accent)=>pw.Container(minHeight:46,padding:const pw.EdgeInsets.symmetric(vertical:7),decoration:pw.BoxDecoration(border:pw.Border(bottom:pw.BorderSide(color:line,width:.6))),child:pw.Row(crossAxisAlignment:pw.CrossAxisAlignment.center,children:[pw.SizedBox(width:35,child:pw.Center(child:icon(d))),pw.SizedBox(width:7),pw.Expanded(child:pw.Column(crossAxisAlignment:pw.CrossAxisAlignment.start,mainAxisAlignment:pw.MainAxisAlignment.center,children:[pw.Text(label,style:pw.TextStyle(font:bold,fontSize:9.4,color:accent)),pw.SizedBox(height:2),pw.Text(value,style:pw.TextStyle(font:regular,fontSize:10.6,color:text))]))]));
    pw.Widget signature(String title,String name,Uint8List? bytes,PdfColor accent)=>pw.Expanded(child:pw.Container(height:88,padding:const pw.EdgeInsets.all(8),decoration:pw.BoxDecoration(border:pw.Border.all(color:line),borderRadius:const pw.BorderRadius.all(pw.Radius.circular(6))),child:pw.Column(crossAxisAlignment:pw.CrossAxisAlignment.start,children:[pw.Row(children:[icon(Icons.draw_outlined,size:15),pw.SizedBox(width:4),pw.Text(title,style:pw.TextStyle(font:bold,fontSize:8.5,color:accent))]),pw.SizedBox(height:4),pw.Expanded(child:pw.Center(child:bytes==null?pw.Text('Assinatura não disponível',style:pw.TextStyle(font:regular,fontSize:7.5,color:PdfColors.grey600)):pw.Image(pw.MemoryImage(bytes),fit:pw.BoxFit.contain))),pw.Container(height:.5,color:line),pw.Text(name,style:pw.TextStyle(font:regular,fontSize:8,color:text),maxLines:1)])));
    for(final x in items){
      final id=_intOrNull(x['id']);Map<String,dynamic> ctx={};if(id!=null){try{ctx=await api.reportContextV23(id);}catch(_){}}
      final inst=_map(ctx['institutional_company']);final companyName=_hasValue(inst['company_name'])?'${inst['company_name']}':'Empresa não cadastrada',companySubtitle='${inst['company_subtitle']??''}',companyDocument='${inst['document']??'-'}',companyAddress='${inst['address']??'-'}';
      final type='${x['type']}',transfer=type=='tank_transfer',fueling=type=='fueling',refinery=type=='refinery_entry';final special=transfer;final accentN=special?PdfColor.fromHex('#9A4D00'):navy,accent=special?PdfColor.fromHex('#E67E22'):royal;
      final own=[if(_hasValue(x['asset_number']))'${x['asset_number']}',if(_hasValue(x['asset_model']))'${x['asset_model']}'].join(' • '),third=[if(_hasValue(x['third_party_plate']))'${x['third_party_plate']}',if(_hasValue(x['third_party_description']))'${x['third_party_description']}'].join(' • ');final equipment=[if(own.isNotEmpty)own,if(third.isNotEmpty)third].join(' + ');
      final title='${_movementLabelForItem(x)}${equipment.isNotEmpty?' • $equipment':''}';final operator='${x['operator']??'-'}',receiver='${x['receiver']??'-'}',nfs=_nfs(ctx);
      final rows=<pw.Widget>[];
      if(refinery){rows.addAll([row(Icons.business_outlined,'Empresa compradora','${ctx['empresa_compradora']??companyName}',accent),row(Icons.business_outlined,'Fornecedor do combustível','${ctx['fornecedor_combustivel']??'-'}',accent),row(Icons.receipt_long_outlined,'Nota Fiscal / lote',nfs,accent),row(Icons.water_drop_outlined,'Combustível','${x['fuel_type']??'-'}',accent),row(Icons.local_gas_station_rounded,'Volume recebido',_br(x['liters'],liters:true),accent),row(Icons.local_shipping_outlined,'Caminhão-tanque','${x['destination_tank']??'-'}',accent),row(Icons.person_outline_rounded,'Quem registrou',operator,accent)]);}
      else if(transfer){rows.addAll([row(Icons.business_outlined,'Empresa','${ctx['empresa']??companyName}',accent),row(Icons.swap_horiz_rounded,'Tipo de movimento','Transferência interna — sem venda',accent),row(Icons.storage_outlined,'Origem','${ctx['origem']??x['source_tank']??'-'}',accent),row(Icons.storage_outlined,'Destino','${ctx['destino']??x['destination_tank']??'-'}',accent),row(Icons.water_drop_outlined,'Volume',_br(x['liters'],liters:true),accent),row(Icons.person_outline_rounded,'Responsável doador','${x['donor_responsible']??operator}',accent),row(Icons.person_outline_rounded,'Responsável recebedor','${x['receiver_responsible']??receiver}',accent),row(Icons.receipt_long_outlined,'NF(s)/Lote(s) envolvidos',nfs,accent)]);}
      else {rows.addAll([row(Icons.business_outlined,'Empresa fornecedora/vendedora do combustível','${ctx['empresa_fornecedora_vendedora']??companyName}',accent),row(Icons.business_outlined,'Empresa recebedora/compradora','${ctx['empresa_recebedora_compradora']??'-'}',accent),row(Icons.location_city_outlined,'Obra','${ctx['obra']??x['work']??'-'}',accent),row(Icons.person_outline_rounded,'Responsável da obra','${ctx['responsavel_obra']??'-'}',accent),row(Icons.precision_manufacturing_outlined,'Equipamento abastecido',equipment.isEmpty?'-':equipment,accent),row(Icons.business_outlined,'Proprietário do equipamento','${ctx['proprietario_equipamento']??'-'}',accent),row(Icons.location_on_outlined,'Localização','${x['location_address']??((x['latitude']!=null&&x['longitude']!=null)?'${x['latitude']}, ${x['longitude']}':'-')}',accent),row(Icons.water_drop_outlined,'Combustível','${x['fuel_type']??'-'}',accent),row(Icons.local_gas_station_rounded,'Volume',_br(x['liters'],liters:true),accent),row(Icons.person_outline_rounded,'Quem recebeu',receiver,accent),row(Icons.person_outline_rounded,'Quem abasteceu',operator,accent),row(Icons.speed_outlined,'KM','${x['km_value']??x['km_hourmeter']??'-'}',accent),row(Icons.speed_outlined,'Horímetro','${x['hourmeter_value']??'-'}',accent),if(x['sale_price_per_liter']!=null)row(Icons.assignment_outlined,'Preço de venda/L',_fmtMoney(x['sale_price_per_liter']),accent),row(Icons.storage_outlined,'Totalizador',_br(x['totalizer']??x['closing_meter'],liters:true),accent),row(Icons.receipt_long_outlined,'NF(s)/Lote(s) utilizados',nfs,accent)]);}
      Uint8List? sig1,sig2;String sig1Name='',sig2Name='',sig1Title='',sig2Title='';if(transfer){sig1=await api.downloadMedia('${x['donor_signature_path']??''}');sig2=await api.downloadMedia('${x['receiver_transfer_signature_path']??x['receiver_signature_path']??''}');sig1Name='${x['donor_responsible']??operator}';sig2Name='${x['receiver_responsible']??receiver}';sig1Title='Assinatura responsável doador';sig2Title='Assinatura responsável recebedor';}else if(fueling){sig1=await api.downloadMedia('${x['receiver_signature_path']??''}');sig2=await api.downloadMedia('${x['operator_signature_path']??''}');sig1Name=receiver;sig2Name=operator;sig1Title='Assinatura de quem recebeu';sig2Title='Assinatura de quem abasteceu';}
      doc.addPage(pw.MultiPage(pageFormat:PdfPageFormat.a4,margin:const pw.EdgeInsets.fromLTRB(30,28,30,24),theme:pw.ThemeData.withFont(base:regular,bold:bold),build:(_)=>[pw.Text(companyName,style:pw.TextStyle(font:bold,fontSize:32,color:accentN)),if(companySubtitle.isNotEmpty)pw.Text(companySubtitle,style:pw.TextStyle(font:regular,fontSize:21,color:accentN)),pw.SizedBox(height:7),pw.Container(height:1.5,color:accent),pw.SizedBox(height:8),pw.Text('CNPJ: $companyDocument',style:pw.TextStyle(font:regular,fontSize:10,color:text)),pw.Text('Endereço: $companyAddress',style:pw.TextStyle(font:regular,fontSize:10,color:text)),pw.SizedBox(height:14),pw.Container(padding:const pw.EdgeInsets.all(14),decoration:pw.BoxDecoration(border:pw.Border.all(color:line),borderRadius:const pw.BorderRadius.all(pw.Radius.circular(10))),child:pw.Column(crossAxisAlignment:pw.CrossAxisAlignment.start,children:[pw.Row(children:[pw.Container(width:48,height:48,decoration:pw.BoxDecoration(color:accentN,shape:pw.BoxShape.circle),child:pw.Center(child:icon(Icons.local_gas_station_rounded,size:24,isWhite:true))),pw.SizedBox(width:12),pw.Expanded(child:pw.Column(crossAxisAlignment:pw.CrossAxisAlignment.start,children:[pw.Text(title,style:pw.TextStyle(font:bold,fontSize:15,color:accentN)),pw.SizedBox(height:3),pw.Text('${_fmtDate(x['created_at'])} • $operator',style:pw.TextStyle(font:regular,fontSize:10.5,color:text))]))]),pw.SizedBox(height:8),...rows,if(_hasValue(x['notes']))row(Icons.assignment_outlined,'Observações','${x['notes']}',accent),if(sig1Title.isNotEmpty)...[pw.SizedBox(height:10),pw.Row(children:[signature(sig1Title,sig1Name,sig1,accent),pw.SizedBox(width:8),signature(sig2Title,sig2Name,sig2,accent)])]])]),pw.SizedBox(height:10),pw.Container(height:1.5,color:accent)]));
      final evidence=<MapEntry<String,String>>[];void add(String l,dynamic v){if(_hasValue(v))evidence.add(MapEntry(l,'$v'));}
      if(refinery){add('Foto da placa do caminhão-tanque',ctx['truck_plate_photo_path']);add('Foto legível da Nota Fiscal',ctx['invoice_photo_path']);if(evidence.isEmpty){final raw=_rowsFromPaths(x['photo_paths']);for(final p in raw){evidence.add(MapEntry('Evidência do recebimento',p));}}}
      if(fueling){add('Foto do KM ou Horímetro',x['meter_photo_path']);add('Foto do Totalizador',x['totalizer_evidence_photo_path']);add('Foto da placa ou identificação',x['identity_evidence_photo_path']);add('Foto do abastecimento',x['extra_evidence_photo_path']);}
      for(final e in evidence){final b=await api.downloadMedia(e.value);if(b==null)continue;doc.addPage(pw.Page(pageFormat:PdfPageFormat.a4,margin:const pw.EdgeInsets.all(30),theme:pw.ThemeData.withFont(base:regular,bold:bold),build:(_)=>pw.Column(crossAxisAlignment:pw.CrossAxisAlignment.start,children:[pw.Text(companyName,style:pw.TextStyle(font:bold,fontSize:24,color:accentN)),pw.Text('Evidências do registro',style:pw.TextStyle(font:bold,fontSize:16,color:accentN)),pw.SizedBox(height:6),pw.Container(height:1.2,color:accent),pw.SizedBox(height:14),pw.Container(width:330,height:500,decoration:pw.BoxDecoration(border:pw.Border.all(color:line),borderRadius:const pw.BorderRadius.all(pw.Radius.circular(6))),child:pw.Padding(padding:const pw.EdgeInsets.all(7),child:pw.Image(pw.MemoryImage(b),fit:pw.BoxFit.contain))),pw.SizedBox(height:6),pw.Text(e.key,style:pw.TextStyle(font:bold,fontSize:10,color:accent))])));}
    }
    return doc.save();
  }
}

'''
s=s[:start]+fuel_pdf+s[end:]

p.write_text(s)
print("business reports part 4 applied",len(s),"chars")
