from pathlib import Path
p=Path('lib/main_online.dart')
s=p.read_text()

anchor="""  Future<List<Map<String,dynamic>>> truckRoles() async => _rows(await client.rpc('rca_truck_roles'));\n"""
insert="""  Future<void> archiveManagedCompany(Map<String,dynamic> x) async {\n    await saveManagedCompany(\n      id:_intOrNull(x['id']),name:'${x['name']??''}',subtitle:'${x['subtitle']??''}',document:'${x['document']??''}',\n      zipCode:'${x['zip_code']??''}',street:'${x['street']??''}',streetNumber:'${x['street_number']??''}',complement:'${x['complement']??''}',\n      neighborhood:'${x['neighborhood']??''}',city:'${x['city']??''}',state:'${x['state']??''}',active:false,\n      isClient:x['is_client']==true,isEquipmentOwner:x['is_equipment_owner']==true,isFuelSupplier:x['is_fuel_supplier']==true,\n    );\n  }\n  Future<void> archiveMachine(Map<String,dynamic> x) async {\n    await saveMachine(\n      id:_intOrNull(x['id']),assetNumber:'${x['numeroAtivo']??x['asset_number']??''}',model:'${x['modelo']??x['model']??''}',plate:'${x['placa']??x['plate']??''}',\n      type:'${x['tipo']??x['type']??''}',location:'${x['localizacao']??x['location']??''}',active:false,\n      comboioCapacityLiters:x['comboio_capacity_liters']==null?null:_num(x['comboio_capacity_liters']),fuelTankCapacityLiters:x['fuel_tank_capacity_liters']==null?null:_num(x['fuel_tank_capacity_liters']),\n      measurementType:'${x['measurement_type']??'none'}'.trim().isEmpty?'none':'${x['measurement_type']}',\n    );\n  }\n  Future<void> archiveThirdParty(Map<String,dynamic> x) async {\n    await saveThirdParty(id:_intOrNull(x['id']),plate:'${x['plate']??''}',company:'${x['company_name']??x['company']??''}',description:'${x['description']??''}',driverName:'${x['driver_name']??''}',active:false);\n  }\n\n"""+anchor
assert anchor in s
s=s.replace(anchor,insert,1)

s=s.replace("if (mounted) setState(() => items = x);","if (mounted) setState(() => items = x.where((e)=>e['active']!=false).toList());",1)
company_build_anchor="""    for (final c in [name, subtitle, document, zip, street, number, complement, neighborhood, city, state]) { c.dispose(); }\n  }\n\n  @override\n  Widget build(BuildContext context) => Scaffold(\n"""
company_remove="""    for (final c in [name, subtitle, document, zip, street, number, complement, neighborhood, city, state]) { c.dispose(); }\n  }\n\n  Future<void> removeCompany(Map<String,dynamic> x) async {\n    final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(\n      title:const Text('Excluir empresa?'),\n      content:Text('“${x['name']}” será retirada dos cadastros ativos e das novas seleções. Todos os abastecimentos, obras, equipamentos, notas, relatórios e auditorias já vinculados continuarão preservados.'),\n      actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancelar')),FilledButton(style:FilledButton.styleFrom(backgroundColor:Colors.red.shade700),onPressed:()=>Navigator.pop(ctx,true),child:const Text('Excluir'))],\n    ));\n    if(ok!=true)return;setState(()=>busy=true);\n    try{await api.archiveManagedCompany(x);await load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Empresa retirada dos cadastros ativos. Histórico preservado ✓')));}\n    catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(_friendlyError(e))));}\n    finally{if(mounted)setState(()=>busy=false);}\n  }\n\n  @override\n  Widget build(BuildContext context) => Scaffold(\n"""
assert company_build_anchor in s
s=s.replace(company_build_anchor,company_remove,1)
old_row="""Row(children: [CircleAvatar(child: Icon(x['is_fuel_supplier']==true ? Icons.local_gas_station_rounded : x['is_equipment_owner']==true ? Icons.precision_manufacturing_outlined : Icons.business_rounded)), const SizedBox(width: 10), Expanded(child: Text('${x['name']}', style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 16))), Icon(x['active']==true ? Icons.check_circle_rounded : Icons.pause_circle_outline_rounded, color: x['active']==true ? Colors.green : Colors.grey), const SizedBox(width: 6), const Icon(Icons.chevron_right_rounded)]),"""
new_row="""Row(children: [CircleAvatar(child: Icon(x['is_fuel_supplier']==true ? Icons.local_gas_station_rounded : x['is_equipment_owner']==true ? Icons.precision_manufacturing_outlined : Icons.business_rounded)), const SizedBox(width: 10), Expanded(child: Text('${x['name']}', style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 16))), IconButton(tooltip:'Excluir sem apagar histórico',onPressed:busy?null:()=>removeCompany(x),icon:const Icon(Icons.delete_outline_rounded,color:Colors.red)), const Icon(Icons.chevron_right_rounded)]),"""
assert old_row in s
s=s.replace(old_row,new_row,1)

machine_anchor="""  @override\n  Widget build(BuildContext context) {\n    final q = filter.text.trim().toLowerCase();\n"""
machine_remove="""  Future<void> removeMachine(Map<String,dynamic> x) async {\n    final label='${x['numeroAtivo']??x['asset_number']??'este ativo'}';\n    final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(\n      title:const Text('Excluir ativo?'),\n      content:Text('$label será retirado dos cadastros ativos e não poderá ser selecionado em novos abastecimentos. Todo o histórico, KM/horímetro, relatórios, fotos e auditoria permanecerão preservados.'),\n      actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancelar')),FilledButton(style:FilledButton.styleFrom(backgroundColor:Colors.red.shade700),onPressed:()=>Navigator.pop(ctx,true),child:const Text('Excluir'))],\n    ));\n    if(ok!=true)return;\n    try{await api.archiveMachine(x);await load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Ativo retirado dos cadastros ativos. Histórico preservado ✓')));}\n    catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(_friendlyError(e))));}\n  }\n"""+machine_anchor
assert machine_anchor in s
s=s.replace(machine_anchor,machine_remove,1)
old_machine_trailing="""onTap: () => edit(x), trailing: const Icon(Icons.edit_outlined))"""
new_machine_trailing="""onTap: () => edit(x), trailing: PopupMenuButton<String>(onSelected:(v){if(v=='edit')edit(x);if(v=='delete')removeMachine(x);},itemBuilder:(_)=>const [PopupMenuItem(value:'edit',child:Text('Editar')),PopupMenuItem(value:'delete',child:Text('Excluir',style:TextStyle(color:Colors.red))) ]))"""
assert old_machine_trailing in s
s=s.replace(old_machine_trailing,new_machine_trailing,1)

third_anchor="""  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Equipamentos de terceiros')),"""
third_remove="""  Future<void> removeThirdParty(Map<String,dynamic> x) async {\n    final label=_hasValue(x['plate'])?'${x['plate']}':'${x['description']??'este equipamento'}';\n    final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(\n      title:const Text('Excluir equipamento de terceiros?'),\n      content:Text('$label será retirado dos cadastros ativos. Todos os abastecimentos, relatórios, fotos, assinaturas e auditorias anteriores permanecerão preservados.'),\n      actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancelar')),FilledButton(style:FilledButton.styleFrom(backgroundColor:Colors.red.shade700),onPressed:()=>Navigator.pop(ctx,true),child:const Text('Excluir'))],\n    ));\n    if(ok!=true)return;setState(()=>loading=true);\n    try{await api.archiveThirdParty(x);await load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Equipamento retirado dos cadastros ativos. Histórico preservado ✓')));}\n    catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(_friendlyError(e))));}\n    finally{if(mounted)setState(()=>loading=false);}\n  }\n"""+third_anchor
assert third_anchor in s
s=s.replace(third_anchor,third_remove,1)
old_third_tile="""onTap:loading?null:()=>edit(x),trailing:const Icon(Icons.edit_outlined))"""
new_third_tile="""onTap:loading?null:()=>edit(x),trailing:PopupMenuButton<String>(enabled:!loading,onSelected:(v){if(v=='edit')edit(x);if(v=='delete')removeThirdParty(x);},itemBuilder:(_)=>const [PopupMenuItem(value:'edit',child:Text('Editar')),PopupMenuItem(value:'delete',child:Text('Excluir',style:TextStyle(color:Colors.red))) ]))"""
assert old_third_tile in s
s=s.replace(old_third_tile,new_third_tile,1)

s=s.replace("child: Text('v65'","child: Text('v66'",1)
p.write_text(s)
print('PATCH_V66_SAFE_DELETE_CATALOGS_OK')
