from pathlib import Path
p=Path('lib/main_online.dart')
s=p.read_text()

def replace_once(old,new,label):
    global s
    if old not in s: raise SystemExit(f'{label}: marcador não encontrado')
    s=s.replace(old,new,1)

old="""  Future<Map<String, dynamic>> adminUpdateMovementCode({required int movementId, required String code}) async {\n    return _map(await client.rpc('rca_admin_update_movement_code', params: {\n      'p_movement_id': movementId,\n      'p_code': code,\n    }));\n  }\n"""
replace_once(old,old+"""\n  Future<Map<String, dynamic>> adminEditFuelingV47({\n    required int movementId, required String code, int? workId, int? machineId, int? thirdPartyVehicleId,\n    double? kmValue, double? hourmeterValue, String? receiverName, String? responsibleName, String? notes, String? locationAddress,\n  }) async => _map(await client.rpc('rca_admin_edit_fueling_v47', params: {\n    'p_movement_id': movementId, 'p_code': code, 'p_work_id': workId, 'p_machine_id': machineId,\n    'p_third_party_vehicle_id': thirdPartyVehicleId, 'p_km_value': kmValue, 'p_hourmeter_value': hourmeterValue,\n    'p_receiver_name': receiverName, 'p_responsible_name': responsibleName, 'p_notes': notes, 'p_location_address': locationAddress,\n  }));\n""",'api')
replace_once("""  List<Map<String,dynamic>> works=[];List<Map<String,dynamic>> items=[];Map<String,dynamic> summary={};bool busy=false;bool filters=true;String? error;final Set<String> selected=<String>{};\n""","""  List<Map<String,dynamic>> works=[];List<Map<String,dynamic>> items=[];Map<String,dynamic> summary={};bool busy=false;bool filters=true;bool isAdmin=false;String? error;final Set<String> selected=<String>{};\n""",'state')
replace_once("""  Future<void> bootstrap() async {try{works=await api.worksCatalogV28();}catch(_){}if(mounted)setState((){});await search(collapse:false);}\n""","""  Future<void> bootstrap() async {try{final values=await Future.wait<dynamic>([api.worksCatalogV28(),api.profile()]);works=(values[0] as List).cast<Map<String,dynamic>>();isAdmin=_map(values[1])['is_admin']==true;}catch(_){try{works=await api.worksCatalogV28();}catch(_){}}if(mounted)setState((){});await search(collapse:false);}\n""",'bootstrap')
replace_once("""onOpen:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>MovementDetailScreen(item:x))),onPdf:()=>preview([x]))))\n""","""onOpen:()async{final changed=await Navigator.push<bool>(context,MaterialPageRoute(builder:(_)=>MovementDetailScreen(item:x,canEdit:isAdmin)));if(changed==true&&mounted)await search(collapse:false);},onPdf:()=>preview([x]))))\n""",'open')
replace_once("""class MovementDetailScreen extends StatelessWidget {\n  final Map<String, dynamic> item;\n  const MovementDetailScreen({super.key, required this.item});\n""","""class MovementDetailScreen extends StatelessWidget {\n  final Map<String, dynamic> item;\n  final bool canEdit;\n  const MovementDetailScreen({super.key, required this.item, this.canEdit=false});\n""",'detail')
replace_once("""        actions: [IconButton(onPressed: () => exportOne(context), tooltip: 'Exportar PDF', icon: const Icon(Icons.picture_as_pdf_outlined))],\n""","""        actions: [\n          if (fueling && canEdit && _intOrNull(item['id']) != null) IconButton(\n            onPressed: () async {\n              final changed=await Navigator.push<bool>(context,MaterialPageRoute(builder:(_)=>AdminEditFuelingV47Screen(item:item)));\n              if(changed==true&&context.mounted)Navigator.pop(context,true);\n            },\n            tooltip:'Editar / corrigir abastecimento',icon:const Icon(Icons.edit_outlined),\n          ),\n          IconButton(onPressed: () => exportOne(context), tooltip: 'Exportar PDF', icon: const Icon(Icons.picture_as_pdf_outlined)),\n        ],\n""",'actions')
editor=r'''class AdminEditFuelingV47Screen extends StatefulWidget {
  final Map<String,dynamic> item;
  const AdminEditFuelingV47Screen({super.key,required this.item});
  @override State<AdminEditFuelingV47Screen> createState()=>_AdminEditFuelingV47ScreenState();
}
class _AdminEditFuelingV47ScreenState extends State<AdminEditFuelingV47Screen>{
  final code=TextEditingController(),km=TextEditingController(),hour=TextEditingController(),receiver=TextEditingController(),responsible=TextEditingController(),notes=TextEditingController(),location=TextEditingController();
  List<Map<String,dynamic>> works=[],machines=[],thirds=[];int? workId,machineId,thirdId;bool loading=true,saving=false;String? error;
  @override void initState(){super.initState();final x=widget.item;code.text='${x['code']??''}';km.text=x['km_value']==null?'':'${x['km_value']}';hour.text=x['hourmeter_value']==null?'':'${x['hourmeter_value']}';receiver.text='${x['receiver']??''}';responsible.text='${x['work_responsible']??''}';notes.text='${x['notes']??''}';location.text='${x['location_address']??''}';workId=_intOrNull(x['work_id']);machineId=_intOrNull(x['asset_id']);thirdId=_intOrNull(x['third_party_vehicle_id']);load();}
  Future<void> load()async{try{final p=await api.profile();if(p['is_admin']!=true)throw Exception('Somente o Admin pode corrigir abastecimentos');final ref=await api.referenceData();final ws=_rows(ref['works']),ms=_rows(ref['machines']),ts=_rows(ref['third_party_vehicles']);if(workId!=null&&!ws.any((x)=>_intOrNull(x['id'])==workId))workId=null;if(machineId!=null&&!ms.any((x)=>_intOrNull(x['id'])==machineId))machineId=null;if(thirdId!=null&&!ts.any((x)=>_intOrNull(x['id'])==thirdId))thirdId=null;if(mounted)setState((){works=ws;machines=ms;thirds=ts;loading=false;});}catch(e){if(mounted)setState((){error=_friendlyError(e);loading=false;});}}
  double? number(TextEditingController c){final t=c.text.trim().replaceAll(',','.');return t.isEmpty?null:double.tryParse(t);}
  Future<void> save()async{if(saving)return;if(code.text.trim().isEmpty){setState(()=>error='Informe a numeração do registro.');return;}if(machineId==null&&thirdId==null){setState(()=>error='Selecione o ativo ou equipamento de terceiros.');return;}final k=number(km),h=number(hour);if((km.text.trim().isNotEmpty&&k==null)||(hour.text.trim().isNotEmpty&&h==null)){setState(()=>error='KM ou horímetro inválido.');return;}setState((){saving=true;error=null;});try{await api.adminEditFuelingV47(movementId:_intOrNull(widget.item['id'])!,code:code.text.trim(),workId:workId,machineId:machineId,thirdPartyVehicleId:thirdId,kmValue:k,hourmeterValue:h,receiverName:receiver.text.trim(),responsibleName:responsible.text.trim(),notes:notes.text.trim(),locationAddress:location.text.trim());if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Abastecimento corrigido com sucesso ✓')));Navigator.pop(context,true);}catch(e){if(mounted)setState(()=>error=_friendlyError(e));}finally{if(mounted)setState(()=>saving=false);}}
  @override void dispose(){for(final c in [code,km,hour,receiver,responsible,notes,location]){c.dispose();}super.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Editar / corrigir abastecimento')),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.fromLTRB(16,16,16,40),children:[
    const Card(child:ListTile(leading:Icon(Icons.admin_panel_settings_outlined,color:_blue),title:Text('Correção exclusiva do Admin',style:TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('A alteração fica registrada na auditoria com os dados anteriores e novos.'))),
    const Card(child:ListTile(leading:Icon(Icons.lock_outline,color:Colors.orange),title:Text('Campos protegidos',style:TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('Litros, origem do combustível, tipo de combustível, coordenadas GPS, fotos, assinaturas, data/hora e operador não podem ser alterados nesta tela para preservar estoque e rastreabilidade.'))),
    if(error!=null)Card(child:ListTile(leading:const Icon(Icons.error_outline,color:Colors.red),title:Text(error!))),
    TextField(controller:code,enabled:!saving,decoration:const InputDecoration(labelText:'Nº do registro *',prefixIcon:Icon(Icons.tag))),const SizedBox(height:10),
    DropdownButtonFormField<int?>(value:workId,isExpanded:true,decoration:const InputDecoration(labelText:'Obra'),items:[const DropdownMenuItem<int?>(value:null,child:Text('Sem obra')),...works.map((x)=>DropdownMenuItem<int?>(value:_intOrNull(x['id']),child:Text('${x['name']}')))],onChanged:saving?null:(v)=>setState(()=>workId=v)),const SizedBox(height:10),
    DropdownButtonFormField<int?>(value:machineId,isExpanded:true,decoration:const InputDecoration(labelText:'Ativo'),items:[const DropdownMenuItem<int?>(value:null,child:Text('Nenhum')),...machines.map((x)=>DropdownMenuItem<int?>(value:_intOrNull(x['id']),child:Text('${x['numeroAtivo']??'-'} • ${x['modelo']??''}')))],onChanged:saving?null:(v)=>setState((){machineId=v;if(v!=null)thirdId=null;})),const SizedBox(height:10),
    DropdownButtonFormField<int?>(value:thirdId,isExpanded:true,decoration:const InputDecoration(labelText:'Equipamento de terceiros'),items:[const DropdownMenuItem<int?>(value:null,child:Text('Nenhum')),...thirds.map((x)=>DropdownMenuItem<int?>(value:_intOrNull(x['id']),child:Text('${x['plate']??'Sem placa'} • ${x['description']??''}')))],onChanged:saving?null:(v)=>setState((){thirdId=v;if(v!=null)machineId=null;})),const SizedBox(height:10),
    Row(children:[Expanded(child:TextField(controller:km,enabled:!saving,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'KM'))),const SizedBox(width:8),Expanded(child:TextField(controller:hour,enabled:!saving,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Horímetro')))]),const SizedBox(height:10),
    TextField(controller:receiver,enabled:!saving,decoration:const InputDecoration(labelText:'Responsável pelo recebimento')),const SizedBox(height:10),
    TextField(controller:responsible,enabled:!saving,decoration:const InputDecoration(labelText:'Responsável da obra')),const SizedBox(height:10),
    TextField(controller:location,enabled:!saving,maxLines:2,decoration:const InputDecoration(labelText:'Endereço / localização textual')),const SizedBox(height:10),
    TextField(controller:notes,enabled:!saving,minLines:3,maxLines:5,decoration:const InputDecoration(labelText:'Observações')),const SizedBox(height:18),
    FilledButton.icon(onPressed:saving?null:save,icon:saving?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.save_outlined),label:Text(saving?'Salvando correção...':'Salvar correção')),
  ]));
}

'''
replace_once("class _RecordDetailData {\n",editor+"class _RecordDetailData {\n",'editor')
p.write_text(s)
print('V47_ADMIN_EDIT_OK')
