from pathlib import Path
p=Path('lib/main_online.dart'); s=p.read_text()

def rep(a,b,n=1):
    global s
    if s.count(a)<n: raise SystemExit('Âncora não encontrada: '+a[:90])
    s=s.replace(a,b,n)

# API: v41, responsável, terceiro manual e preço real para PDF.
a="  Future<Map<String,dynamic>> fuelingV22({required int sourceTankId,int? workId,int? machineId,int? thirdId,required double liters,double? km,double? hourmeter,required String receiver,required String receiverSignature,required String operatorSignature,String? meterPhoto,required String totalizerPhoto,required String identityPhoto,required String identityKind,String? extraPhoto,double? salePrice,String? notes,required String fuelType,required String location,double? latitude,double? longitude,DateTime? locationCapturedAt,double? locationAccuracyM}) async => offlineStore.executeOrQueue('rca_record_fueling_v33',{'p_source_tank_id':sourceTankId,'p_work_id':workId,'p_machine_id':machineId,'p_third_party_vehicle_id':thirdId,'p_third_party_plate':null,'p_third_party_company':null,'p_third_party_description':null,'p_liters':liters,'p_km_value':km,'p_hourmeter_value':hourmeter,'p_receiver_name':receiver,'p_receiver_company':null,'p_receiver_signature_path':receiverSignature,'p_operator_signature_path':operatorSignature,'p_meter_photo_path':meterPhoto,'p_totalizer_photo_path':totalizerPhoto,'p_identity_photo_path':identityPhoto,'p_identity_evidence_kind':identityKind,'p_extra_photo_path':extraPhoto,'p_sale_price_per_liter':salePrice,'p_notes':notes,'p_lubricated':false,'p_latitude':latitude,'p_longitude':longitude,'p_fuel_type':fuelType,'p_location_address':location,'p_location_captured_at':locationCapturedAt?.toUtc().toIso8601String(),'p_location_accuracy_m':locationAccuracyM});"
b="  Future<Map<String,dynamic>> fuelingV22({required int sourceTankId,int? workId,int? machineId,int? thirdId,String? thirdPartyPlate,String? thirdPartyDescription,required double liters,double? km,double? hourmeter,String? responsible,required String receiver,required String receiverSignature,required String operatorSignature,String? meterPhoto,required String totalizerPhoto,required String identityPhoto,required String identityKind,String? extraPhoto,double? salePrice,String? notes,required String fuelType,required String location,double? latitude,double? longitude,DateTime? locationCapturedAt,double? locationAccuracyM}) async => offlineStore.executeOrQueue('rca_record_fueling_v41',{'p_source_tank_id':sourceTankId,'p_work_id':workId,'p_machine_id':machineId,'p_third_party_vehicle_id':thirdId,'p_third_party_plate':thirdPartyPlate,'p_third_party_company':null,'p_third_party_description':thirdPartyDescription,'p_liters':liters,'p_km_value':km,'p_hourmeter_value':hourmeter,'p_responsible_name':responsible,'p_receiver_name':receiver,'p_receiver_company':null,'p_receiver_signature_path':receiverSignature,'p_operator_signature_path':operatorSignature,'p_meter_photo_path':meterPhoto,'p_totalizer_photo_path':totalizerPhoto,'p_identity_photo_path':identityPhoto,'p_identity_evidence_kind':identityKind,'p_extra_photo_path':extraPhoto,'p_sale_price_per_liter':salePrice,'p_notes':notes,'p_lubricated':false,'p_latitude':latitude,'p_longitude':longitude,'p_fuel_type':fuelType,'p_location_address':location,'p_location_captured_at':locationCapturedAt?.toUtc().toIso8601String(),'p_location_accuracy_m':locationAccuracyM});\n  Future<Map<String,dynamic>> pdfSaleV41(int movementId) async => _map(await client.rpc('rca_pdf_sale_v41',params:{'p_movement_id':movementId}));"
rep(a,b)
rep("final liters=TextEditingController(),km=TextEditingController(),hour=TextEditingController(),receiver=TextEditingController(),location=TextEditingController(),sale=TextEditingController();","final liters=TextEditingController(),km=TextEditingController(),hour=TextEditingController(),responsible=TextEditingController(),receiver=TextEditingController(),location=TextEditingController(),sale=TextEditingController(),thirdDescription=TextEditingController(),thirdPlate=TextEditingController();")

rep("if(st!=null)targets.add('${_hasValue(st['plate'])?st['plate']:'Sem placa'} • ${st['description']??''}');","if(st!=null)targets.add('${_hasValue(st['plate'])?st['plate']:'Sem placa'} • ${st['description']??''}');\n    if(st==null&&thirdPlate.text.trim().isNotEmpty)targets.add('${thirdPlate.text.trim()} • ${thirdDescription.text.trim()}');")
rep("const SizedBox(height:8),Text('Combustível: $fuel')","const SizedBox(height:8),if(responsible.text.trim().isNotEmpty)Text('Responsável: ${responsible.text.trim()}'),Text('Combustível: $fuel')")

rep("if(machine==null&&third==null){requiredMessage('Ativo ou Equipamento de terceiros');return;}\n    if(kinds.contains('km')){k=double.tryParse(km.text.trim().replaceAll(',','.'));if(k==null||k<0){requiredMessage('KM');return;}}\n    if(kinds.contains('hour')){h=double.tryParse(hour.text.trim().replaceAll(',','.'));if(h==null||h<0){requiredMessage('Horímetro');return;}}","final manualThird=machine==null&&third==null&&(thirdDescription.text.trim().isNotEmpty||thirdPlate.text.trim().isNotEmpty);\n    if(machine==null&&third==null&&!manualThird){requiredMessage('Ativo ou Equipamento de terceiros');return;}\n    if(manualThird&&thirdPlate.text.trim().isEmpty){requiredMessage('Placa/Identificação');return;}\n    if(manualThird){k=double.tryParse(km.text.trim().replaceAll(',','.'));h=double.tryParse(hour.text.trim().replaceAll(',','.'));if(k!=null&&k<0){requiredMessage('KM');return;}if(h!=null&&h<0){requiredMessage('Horímetro');return;}if(k==null&&h==null){requiredMessage('KM ou Horímetro');return;}}else{if(kinds.contains('km')){k=double.tryParse(km.text.trim().replaceAll(',','.'));if(k==null||k<0){requiredMessage('KM');return;}}if(kinds.contains('hour')){h=double.tryParse(hour.text.trim().replaceAll(',','.'));if(h==null||h<0){requiredMessage('Horímetro');return;}}}")
rep("if(kinds.isNotEmpty&&meter==null){requiredMessage(kinds.length>1?'Foto de KM/Horímetro':kinds.contains('km')?'Foto do KM':'Foto do Horímetro');return;}","if((kinds.isNotEmpty||manualThird)&&meter==null){requiredMessage(kinds.length>1?'Foto de KM/Horímetro':kinds.contains('km')?'Foto do KM':kinds.contains('hour')?'Foto do Horímetro':'Foto de KM/Horímetro');return;}")

rep("final r=await api.fuelingV22(sourceTankId:_intOrNull(widget.source['id'])!,workId:work,machineId:machine,thirdId:third,liters:v,km:k,hourmeter:h,receiver:receiver.text.trim()","final manualThird=machine==null&&third==null&&thirdPlate.text.trim().isNotEmpty;\n      final r=await api.fuelingV22(sourceTankId:_intOrNull(widget.source['id'])!,workId:work,machineId:machine,thirdId:third,thirdPartyPlate:manualThird?thirdPlate.text.trim():null,thirdPartyDescription:manualThird?thirdDescription.text.trim():null,liters:v,km:k,hourmeter:h,responsible:responsible.text.trim(),receiver:receiver.text.trim()")
rep("identityKind:hasPlate?'plate':'side'","identityKind:(hasPlate||manualThird)?'plate':'side'")
rep("for(final c in [liters,km,hour,receiver,location,sale])","for(final c in [liters,km,hour,responsible,receiver,location,sale,thirdDescription,thirdPlate])")

rep("final sm=selected(ms,machine),st=selected(ts,third),sw=selected(ws,work),hasPlate=_hasValue(sm?['placa'])||_hasValue(st?['plate']);","final sm=selected(ms,machine),st=selected(ts,third),sw=selected(ws,work),manualThird=machine==null&&third==null&&(thirdDescription.text.trim().isNotEmpty||thirdPlate.text.trim().isNotEmpty),hasPlate=_hasValue(sm?['placa'])||_hasValue(st?['plate'])||manualThird;")
rep("onChanged:saving?null:(v)=>setState(()=>work=v)),\n      if(needsWork&&_hasValue(sw?['responsible']))Padding(padding:const EdgeInsets.only(top:6),child:Text('Responsável da obra: ${sw?['responsible']}',style:const TextStyle(fontWeight:FontWeight.w700))),if(needsWork)const SizedBox(height:12),","onChanged:saving?null:(v){setState(()=>work=v);final w=selected(ws,v);if(responsible.text.trim().isEmpty&&_hasValue(w?['responsible']))responsible.text='${w?['responsible']}';}),\n      const SizedBox(height:8),TextField(controller:responsible,enabled:!saving,decoration:const InputDecoration(labelText:'Responsável')),const SizedBox(height:12),")
rep("labelText:'Equipamento de terceiros')","labelText:'Selecionar equipamento de terceiros cadastrado (opcional)')",1)
s=s.replace("decoration:const InputDecoration(labelText:'Selecionar equipamento de terceiros cadastrado (opcional)')))","decoration:const InputDecoration(labelText:'Selecionar equipamento de terceiros cadastrado (opcional)'))",1)
rep("onChanged:saving?null:(v)=>setState(()=>third=v)),\n      const Padding(padding:EdgeInsets.only(top:6,bottom:10),child:Text('Selecione pelo menos um destino.',style:TextStyle(fontSize:12,color:Colors.black54))),","onChanged:saving?null:(v){setState(()=>third=v);final t=selected(ts,v);if(t!=null){thirdPlate.text='${t['plate']??''}';thirdDescription.text='${t['description']??''}';}else{thirdPlate.clear();thirdDescription.clear();}}),\n      const SizedBox(height:8),TextField(controller:thirdDescription,enabled:!saving&&third==null,onChanged:(_)=>setState((){}),decoration:const InputDecoration(labelText:'Equipamento de terceiros')),\n      const SizedBox(height:8),TextField(controller:thirdPlate,enabled:!saving&&third==null,onChanged:(_)=>setState((){}),decoration:const InputDecoration(labelText:'Placa/Identificação')),\n      const Padding(padding:EdgeInsets.only(top:6,bottom:10),child:Text('Selecione um ativo, escolha um equipamento de terceiros cadastrado ou preencha os dados do equipamento de terceiros.',style:TextStyle(fontSize:12,color:Colors.black54))),")
rep("if(needsKm&&needsHour)Row(children:","if(manualThird)Row(children:[Expanded(child:TextField(controller:km,enabled:!saving,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'KM'))),const SizedBox(width:8),Expanded(child:TextField(controller:hour,enabled:!saving,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Horímetro')))])\n      else if(needsKm&&needsHour)Row(children:")
rep("if(kinds.isNotEmpty)const Padding(padding:EdgeInsets.only(top:5),child:Text('O sistema solicita a medição configurada no cadastro do ativo.',style:TextStyle(fontSize:12,color:Colors.black54))),","if(manualThird)const Padding(padding:EdgeInsets.only(top:5),child:Text('Para equipamento de terceiros preenchido manualmente, informe KM ou Horímetro conforme o equipamento.',style:TextStyle(fontSize:12,color:Colors.black54)))\n      else if(kinds.isNotEmpty)const Padding(padding:EdgeInsets.only(top:5),child:Text('O sistema solicita a medição configurada no cadastro do ativo.',style:TextStyle(fontSize:12,color:Colors.black54))),")
rep("if(kinds.isNotEmpty)OutlinedButton(onPressed:saving?null:()async{final x=await cam();if(x!=null)setState(()=>meter=x);}","if(kinds.isNotEmpty||manualThird)OutlinedButton(onPressed:saving?null:()async{final x=await cam();if(x!=null)setState(()=>meter=x);}")

rep("final refinery = type == 'refinery_entry';","final refinery = type == 'refinery_entry';\n      Map<String,dynamic> pdfSale={};\n      if(fueling&&id!=null){try{pdfSale=await api.pdfSaleV41(id);}catch(_){}}")
rep("final salePriceValue = _num(x['sale_price_per_liter']);\n        final totalSaleValue = x['sale_total'] ?? x['total_value'] ?? (litersValue * salePriceValue);","final salePriceRaw = pdfSale['sale_price_per_liter'] ?? x['sale_price_per_liter'];\n        final salePriceValue = _num(salePriceRaw);\n        final totalSaleValue = pdfSale['total_value'] ?? x['sale_total'] ?? x['total_value'] ?? (litersValue * salePriceValue);")
rep("'Responsável da obra', '${ctx['responsavel_obra'] ?? '-'}","'Responsável', '${ctx['responsavel_obra'] ?? '-'}")
rep("'Preço de venda/L', x['sale_price_per_liter'] == null ? '-' : _fmtMoney(x['sale_price_per_liter'])","'Preço de venda/L', salePriceRaw == null ? '-' : _fmtMoney(salePriceRaw)")
rep("'Valor total', x['sale_price_per_liter'] == null ? '-' : _fmtMoney(totalSaleValue)","'Valor total', salePriceRaw == null ? '-' : _fmtMoney(totalSaleValue)")

p.write_text(s)
print('V41_FUELING_FIELDS_PDF_OK')
