from pathlib import Path
p=Path('lib/main_online.dart')
s=p.read_text()
old="""      Text('Origem: ${widget.source['code']} • ${widget.source['name']}',style:const TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:8),Text('Ativo/equipamento: ${targets.join(' + ')}'),const SizedBox(height:8),Text('Combustível: $fuel'),Text('Volume: ${_fmtLiters(v)}'),if(k!=null)Text('KM: ${k.toStringAsFixed(k.truncateToDouble()==k?0:1)}'),if(h!=null)Text('Horímetro: ${h.toStringAsFixed(h.truncateToDouble()==h?0:1)}'),Text('Responsável pelo recebimento do abastecimento: ${receiver.text.trim()}'),if(observation.text.trim().isNotEmpty)Text('Observação: ${observation.text.trim()}'),const SizedBox(height:8),Text('Endereço do abastecimento: ${location.text.trim()}',style:const TextStyle(fontWeight:FontWeight.w700)),Text(manualLocationV44?'Localização informada manualmente':'Localização obtida automaticamente',style:const TextStyle(fontSize:12,color:Colors.black54)),if(capturedPosition!=null)Text('Coordenadas: ${capturedPosition!.latitude.toStringAsFixed(6)}, ${capturedPosition!.longitude.toStringAsFixed(6)}',style:const TextStyle(fontSize:12,color:Colors.black54)),if(capturedPosition!=null)Text(locationMeta(),style:const TextStyle(fontSize:12,color:Colors.black54)),const SizedBox(height:10),const Text('Confira os dados antes de confirmar. Depois da confirmação o registro será processado.')
"""
new="""      Text('Origem: ${widget.source['code']} • ${widget.source['name']}',style:const TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:8),Text('Ativo/equipamento: ${targets.join(' + ')}'),const SizedBox(height:8),Text('Combustível: $fuel'),Text('Volume: ${_fmtLiters(v)}'),Text('Preço por litro: ${_fmtMoney(_num(sale.text.replaceAll(',', '.')))}'),Text('Valor total: ${_fmtMoney(v*_num(sale.text.replaceAll(',', '.')))}',style:const TextStyle(fontWeight:FontWeight.w700)),if(k!=null)Text('KM: ${k.toStringAsFixed(k.truncateToDouble()==k?0:1)}'),if(h!=null)Text('Horímetro: ${h.toStringAsFixed(h.truncateToDouble()==h?0:1)}'),Text('Responsável pelo recebimento do abastecimento: ${receiver.text.trim()}'),if(observation.text.trim().isNotEmpty)Text('Observação: ${observation.text.trim()}'),const SizedBox(height:8),Text('Endereço do abastecimento: ${location.text.trim()}',style:const TextStyle(fontWeight:FontWeight.w700)),Text(manualLocationV44?'Localização informada manualmente':'Localização obtida automaticamente',style:const TextStyle(fontSize:12,color:Colors.black54)),if(capturedPosition!=null)Text('Coordenadas: ${capturedPosition!.latitude.toStringAsFixed(6)}, ${capturedPosition!.longitude.toStringAsFixed(6)}',style:const TextStyle(fontSize:12,color:Colors.black54)),if(capturedPosition!=null)Text(locationMeta(),style:const TextStyle(fontSize:12,color:Colors.black54)),const SizedBox(height:10),const Text('Confira os dados antes de confirmar. Depois da confirmação o registro será processado.')
"""
assert old in s
s=s.replace(old,new,1)
s=s.replace("child: Text('v66'","child: Text('v67'",1)
p.write_text(s)
print('PATCH_V67_CONFIRMATION_PRICE_TOTAL_OK')
